### ISSUE TITLE
NullPointerException: Camera1Controller.switchCamera (Camera1Controller.java:105)

### ISSUE THREAD

**Issue by jdgd** [florent37/CameraFragment#1]
Got the following exception on Sony C1504, Android 4.1.1 (rooted):

Fatal Exception: java.lang.NullPointerException       at com.github.florent37.camerafragment.internal.controller.impl.Camera1Controller.switchCamera(Camera1Controller.java:105)       at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.switchCameraTypeFrontBack(BaseAnncaFragment.java:421)       at com.dgtalgroup.retailmonitor.gui.activities.CameraActivity.toggleCamara(CameraActivity.java:111)       at com.dgtalgroup.retailmonitor.gui.activities.CameraActivity$$ViewBinder$1.doClick(CameraActivity$$ViewBinder.java:18)
       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
       at android.view.View.performClick(View.java:4106)
       at android.view.View$PerformClick.run(View.java:17150)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4793)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by alfaro28** [comment]
Here is the crash log from crashlytics [crash.txt](https://github.com/florent37/CameraFragment/files/750976/crash.txt)
