### ISSUE TITLE
camera crash when flash is on

### ISSUE THREAD

**Issue by morteza0001** [florent37/CameraFragment#101]
when flash is on get error
`Error setting flash: 
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
                                                                      at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.setFlashModeAndBuildPreviewRequest(Camera2Manager.java:708)
                                                                      at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.setFlashMode(Camera2Manager.java:235)
                                                                      at com.github.florent37.camerafragment.internal.controller.impl.Camera2Controller.setFlashMode(Camera2Controller.java:130)
                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.onFlashModeChanged(BaseAnncaFragment.java:504)
                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.setFlashMode(BaseAnncaFragment.java:556)
                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.onViewCreated(BaseAnncaFragment.java:255)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
                                                                      at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:461)
                                                                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
                                                                      at android.app.Activity.performResume(Activity.java:7017)
                                                                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3561)
                                                                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                      at android.os.Looper.loop(Looper.java:156)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
04-07 06:49:34.511 13224-13224/ir.morteza.baran E/Camera2Manager: Error setting flash: 
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
                                                                      at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.setFlashModeAndBuildPreviewRequest(Camera2Manager.java:708)
                                                                      at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.setFlashMode(Camera2Manager.java:235)
                                                                      at com.github.florent37.camerafragment.internal.controller.impl.Camera2Controller.setFlashMode(Camera2Controller.java:130)
                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.onFlashModeChanged(BaseAnncaFragment.java:504)
                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.notifyListeners(BaseAnncaFragment.java:277)
                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.onViewCreated(BaseAnncaFragment.java:272)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
                                                                      at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:461)
                                                                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
                                                                      at android.app.Activity.performResume(Activity.java:7017)
                                                                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3561)
                                                                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                      at android.os.Looper.loop(Looper.java:156)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
04-07 06:49:34.513 13224-13907/ir.morteza.baran E/CameraHelper: Couldn't find any suitable preview size
04-07 06:49:34.606 13224-13907/ir.morteza.baran E/CameraHelper: Couldn't find any suitable preview size
04-07 06:49:34.623 13224-13224/ir.morteza.baran E/Camera2Manager: Error while preparing surface for preview: 
                                                                  android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): checkPidStatus:1096: The camera device has been disconnected
                                                                      at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:633)
                                                                      at android.hardware.camera2.impl.ICameraDeviceUserWrapper.createDefaultRequest(ICameraDeviceUserWrapper.java:159)
                                                                      at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:665)
                                                                      at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.startPreview(Camera2Manager.java:371)
                                                                      at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.onSurfaceTextureAvailable(Camera2Manager.java:771)
                                                                      at android.view.TextureView.getHardwareLayer(TextureView.java:394)
                                                                      at android.view.TextureView.draw(TextureView.java:330)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16201)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16196)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.draw(View.java:17239)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16201)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16196)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16196)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16196)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16196)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16196)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16196)
                                                                      at android.view.View.draw(View.java:17002)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                      at android.view.View.draw(View.java:17239)
                                                                      at com.android.internal.policy.DecorView.draw(DecorView.java:801)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16201)
                                                                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
                                                                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
                                                                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:796)
                                                                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2991)
                                                                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2785)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2376)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1366)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6768)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
04-07 06:49:34.623 13224-13224/ir.morteza.baran E/Camera2Manager:     at android.os.Handler.handleCallback(Handler.java:761)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:156)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                   Caused by: android.os.ServiceSpecificException: checkPidStatus:1096: The camera device has been disconnected
                                                                      at android.os.Parcel.readException(Parcel.java:1679)
                                                                      at android.os.Parcel.readException(Parcel.java:1618)
                                                                      at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.createDefaultRequest(ICameraDeviceUser.java:503)
                                                                      at android.hardware.camera2.impl.ICameraDeviceUserWrapper.createDefaultRequest(ICameraDeviceUserWrapper.java:157)`

**Comment by sivasonai** [comment]
Are you solve this issue, I'm also getting the same issue in one plus version 9. Please help me to solve this issue.

**Comment by angelmarrugo** [comment]
me too
