### ISSUE TITLE
release camera.

### ISSUE THREAD

**Issue by bhoomprajapati** [florent37/CameraFragment#29]

**Comment by dark1991** [comment]
: FATAL EXCEPTION: main
                                                                              Process: com.enclaveit.ezfaxing.debug, PID: 30334
                                                                              java.lang.RuntimeException: Method called after release()
                                                                                  at android.hardware.Camera.native_getParameters(Native Method)
                                                                                  at android.hardware.Camera.getParameters(Camera.java:2674)
                                                                                  at com.github.florent37.camerafragment.internal.manager.impl.Camera1Manager.getPhotoSizeForQuality(Camera1Manager.java:261)
                                                                                  at com.github.florent37.camerafragment.internal.manager.impl.Camera1Manager.getPhotoQualityOptions(Camera1Manager.java:624)
                                                                                  at com.github.florent37.camerafragment.internal.controller.impl.Camera1Controller.getPhotoQualityOptions(Camera1Controller.java:210)
                                                                                  at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.setCameraPreview(BaseAnncaFragment.java:643)
                                                                                  at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment$3.updateCameraPreview(BaseAnncaFragment.java:183)
                                                                                  at com.github.florent37.camerafragment.internal.controller.impl.Camera1Controller.onCameraOpened(Camera1Controller.java:158)
                                                                                  at com.github.florent37.camerafragment.internal.controller.impl.Camera1Controller.onCameraOpened(Camera1Controller.java:30)
                                                                                  at com.github.florent37.camerafragment.internal.manager.impl.Camera1Manager$1$1.run(Camera1Manager.java:73)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:155)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by wengelef** [comment]
+1

Samsung Galaxy S5 (SM-G00F), 6.0.1
