### ISSUE TITLE
NullPointerException:Camera2Manager.openCamera (Camera2Manager.java:182)

### ISSUE THREAD

**Issue by jdgd** [florent37/CameraFragment#4]
Phone: HUAWEI VNS-L53, Android 6.0

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
       at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.openCamera(Camera2Manager.java:182)
       at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.openCamera(Camera2Manager.java:56)
       at com.github.florent37.camerafragment.internal.controller.impl.Camera2Controller.onCameraClosed(Camera2Controller.java:156)
       at com.github.florent37.camerafragment.internal.controller.impl.Camera2Controller.onCameraClosed(Camera2Controller.java:31)
       at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager$4$1.run(Camera2Manager.java:225)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5639)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

**Comment by hntandroid** [comment]
i am also getting same error when i use instant run on Android Studio while opening camera fragment
