### ISSUE TITLE
ImageSaver, IllegalStateException: Image is already closed

### ISSUE THREAD

**Issue by yku-yku** [florent37/CameraFragment#50]
Application crash with IllegalStateException:

Terminating app due to an uncaught exception 'java.lang.IllegalStateException', reason: 'Image is already closed'

0 | java.lang.IllegalStateException: Image is already closed
1 | at android.media.Image.throwISEIfImageIsInvalid(Image.java:68)
2 | at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:733)
3 | at com.github.florent37.camerafragment.internal.utils.ImageSaver.run(ImageSaver.java:39)
4 | at android.os.Handler.handleCallback(Handler.java:751)
5 | at android.os.Handler.dispatchMessage(Handler.java:95)
6 | at android.os.Looper.loop(Looper.java:154)
7 | at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yku-yku** [comment]
Here is the fix, how should I create 
``

**Comment by yku-yku** [comment]
#51

**Comment by sallison117** [comment]
I know this says this is resolved in Issue #51 but I am still getting the crash reported. 
com.github.florent37.camerafragment.internal.utils.ImageSaver.run (ImageSaver.java:39)
It is happening on a couple of LG phone my users are using running 7. This is the gradle compile 'com.github.florent37:camerafragment:1.0.7' am I not on the newest version this is what the project said to use. Help would be much appreciated.

**Comment by sallison117** [comment]
Ok so I just went back through the page and it does say 1.0.8 so I will move up. Take should probably work.

**Comment by BalajiVasu-Rntbci** [comment]
Please try calling the super() after getting the bitmap. In my case I added the super after getting bitmap in my image capture listener. Solved the above crash issue

imageProxy.image?.let { it ->
                    val bitmap = it.toBitmap()
                    bitmap?.let {
                          imgView.setImageBitmap(bitmap)
                    }
                    super.onCaptureSuccess(imageProxy)
                }
