### ISSUE TITLE
Error While setup camera sizes.

### ISSUE THREAD

**Issue by premacck** [florent37/CameraFragment#62]
I have tried it on multiple devices, but the issue is persistent.
Whenever I open the camera the app crashes, giving the following log:

```
09-21 15:20:43.786 24476-24476/com.cncoding.teazer I/CameraManagerGlobal: Connecting to camera service
09-21 15:20:43.939 24476-24663/com.cncoding.teazer E/Camera1Manager: Error while setup camera sizes.
09-21 15:20:43.981 24476-24476/com.cncoding.teazer D/AndroidRuntime: Shutting down VM
09-21 15:20:43.982 24476-24476/com.cncoding.teazer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.cncoding.teazer, PID: 24476
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.florent37.camerafragment.internal.utils.Size.getHeight()' on a null object reference
                                                                         at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.setCameraPreview(BaseAnncaFragment.java:649)
                                                                         at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment$3.updateCameraPreview(BaseAnncaFragment.java:183)
                                                                         at com.github.florent37.camerafragment.internal.controller.impl.Camera1Controller.onCameraOpened(Camera1Controller.java:158)
                                                                         at com.github.florent37.camerafragment.internal.controller.impl.Camera1Controller.onCameraOpened(Camera1Controller.java:30)
                                                                         at com.github.florent37.camerafragment.internal.manager.impl.Camera1Manager$1$1.run(Camera1Manager.java:73)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by ishaan-khan** [comment]
I am getting the same issue.
Devices:
Redmi Note 5 Pro
Mi A1
Redmi 5A
Any solution or workaround?
