### ISSUE TITLE
Exception. No video recording, only minimal size works.

### ISSUE THREAD

**Issue by einschneidend** [florent37/CameraFragment#86]
When recording video the app freezes with an still image,
when stop is pressed video is generated with file size 0,
this does not happens on minimal resolution, that one
works OK.

Following exception is thrown.

`01-29 17:41:28.872 31949-31964/com.github.florent37.camerafragment.sample E/Legacy-CameraDevice-JNI: LegacyCameraDevice_nativeDetectSurfaceDimens: Error while querying surface width No such device (-19).
01-29 17:41:28.877 31949-31964/com.github.florent37.camerafragment.sample E/Camera2Manager: startVideoRecord: 
                                                                                            java.lang.IllegalArgumentException: Surface was abandoned
                                                                                                at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:70)
                                                                                                at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:202)
                                                                                                at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:96)
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:492)
                                                                                                at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager$6.run(Camera2Manager.java:291)
                                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                             Caused by: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
                                                                                                at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:73)
                                                                                                at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:585)
                                                                                                at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:68)
                                                                                                at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:202) 
                                                                                                at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:96) 
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:492) 
                                                                                                at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager$6.run(Camera2Manager.java:291) 
                                                                                                at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                                at android.os.HandlerThread.run(HandlerThread.java:61) `

Tested on a Nexus 6 and a Samsung S6.

Thanks.

**Comment by sagartrehan** [comment]
@einschneidend
Did you get the solution

**Comment by einschneidend** [comment]
Hi, Yes, in CameraHelper.java I changed this
` public static Size getSizeWithClosestRatio(Size[] sizes, int width, int height) {
...
 if (Math.abs(ratio - targetRatio) <= MIN_TOLERANCE) {
                MIN_TOLERANCE = Math.abs(ratio - targetRatio);
                //minDiff = Double.MAX_VALUE;
            }
            else continue;
...
`

**Comment by spartyboy** [comment]
> Hi, yes, in CameraHelper.java I changed this
> `public static Size getSizeWithClosestRatio(Size[] sizes, int width, int height) { ... if (Math.abs(ratio - targetRatio) <= MIN_TOLERANCE) { MIN_TOLERANCE = Math.abs(ratio - targetRatio); //minDiff = Double.MAX_VALUE; } else continue; ...`

same issue at my end here is there  a solution to this can't edit camerahelper as its readonly
