### ISSUE TITLE
Camera2Manager.setFlashModeAndPrevieRequest NullPointerException on

### ISSUE THREAD

**Issue by laszlo-galosi** [florent37/CameraFragment#9]
Looks like when Camera2Controller.setFlashMode have been called, from BaseAncaFragment onFlashModeChanged. The Camera2Manager previewRequestBuilder is null resulting this:

Error setting flash: 
                                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
                                                                                      at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.setFlashModeAndBuildPreviewRequest(Camera2Manager.java:705)
                                                                                      at com.github.florent37.camerafragment.internal.manager.impl.Camera2Manager.setFlashMode(Camera2Manager.java:235)
                                                                                      at com.github.florent37.camerafragment.internal.controller.impl.Camera2Controller.setFlashMode(Camera2Controller.java:112)
                                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.onFlashModeChanged(BaseAnncaFragment.java:500)
                                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.setFlashMode(BaseAnncaFragment.java:552)
                                                                                      at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.onViewCreated(BaseAnncaFragment.java:255)

**Comment by rahulmenezes** [comment]
Experiencing the same issue. Any updates on a solution?

**Comment by sagartrehan** [comment]
@rahulmenezes @laszlo-galosi @florent37 
Did you get the solution for this issue?
